# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            files: ".*py"
          - id: check-yaml
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-json
          # - id: check-shebang-scripts-are-executable
          # - id: pretty-format-json
          # - id: check-merge-conflict
          - id: check-toml
          # - id: detect-aws-credentials
          - id: detect-private-key
          - id: fix-byte-order-marker
          - id: mixed-line-ending
    # - repo: https://github.com/psf/black
    #   rev: 21.5b1
    #   hooks:
    #       - id: black
    # - repo: https://github.com/nbQA-dev/nbQA
    #   rev: 1.1.0
    #   hooks:
    #   - id: nbqa-black
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.5.7
      hooks:
          - id: autopep8
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.6.0
      hooks:
          - id: reorder-python-imports
        # - repo: https://gitlab.com/pycqa/flake8
    #   rev: 3.9.2
    #   hooks:
    #     - id: flake8
    #       args:
    #         - "--max-line-length=200"
    #         - "--ignore=E266,W503,E731,E722,E203,E741,W504,W605,E402"
    # - repo: https://github.com/myint/autoflake
    #   rev: v1.4
    #   hooks:
    #     - id: autoflake
    #       args:
    #       - "--in-place"
    #       - "--remove-all-unused-imports"
    #       - "--remove-unused-variable"
    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.0
      hooks:
      -  id: absolufy-imports
